GET http://localhost:3000/api/hello

@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..2wHie3uGNwuaT0D8.DFuHGBwTvmgo2X5N0urm0EYOaAymXKyE3jNFPKNBNSK9DshEudRn5MeS5FaehfcWr80PvhLQvEHiOC5C0RmgtXa_PacEsvw-xYJ7jjkWdA2Lpip1NfefJZjBeGgtOgjihCcJEL08fSkUSJ8RzlOyGcLT3ZNxse3gi2m6AADVRA8tRkaZQR46zg0gfUc.TOvHiRkt_Si9uTScjLENoA
###
POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Hello World-1"
}

###
GET http://localhost:3000/api/chats
Authorization: Bearer {{token}}

###
@chatId = bb942b0d-7e3e-4348-9dd7-b9fbcb030ced

GET http://localhost:3000/api/chats/{{chatId}}/messages
Authorization: Bearer {{token}}

###
@messageId = c9673b7f-2ab8-4b1b-a672-fae2fa5dd5e4
GET http://localhost:3000/api/chats/{{messageId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{

}

###
GET http://localhost:3000/api/event-stream

